site_name: TamerOnline Docs
site_url: https://tameronline.github.io/resume-templates/

theme:
  name: material


nav:
  - Two Column Dynamic: two-column-dynamic.md

plugins:
  - search
  - git-revision-date
  - macros



