site_name: TamerOnline Docs
site_url: https://tameronline.github.io/pro-gh-pages/

theme:
  name: material

plugins:
  - search
  - awesome-pages
  - include-markdown
  - git-revision-date
  - macros


