site_name: Templates Docs
site_url: https://tameronline.github.io/resume-templates/

theme:
  name: material
  custom_dir: overrides
  features:
    - search.highlight
    - search.suggest

plugins:
  - search
  - macros
  - awesome-pages

extra:
  generator: false
  copyright: © 2025 Tamer Hamad Faour – All rights reserved | <a href="https://github.com/tameronline/resume-templates" target="_blank">GitHub</a>





